# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('collection', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
            ],
        ),
    ]
